### ISSUE TITLE
Preview generator rotating the image by 90 degrees clockwise while generating thumbnail

### ISSUE THREAD

**Issue by AbhijitKulkarni95** [algoo/preview-generator#212]
Preview generator rotating the image by 90 degrees clockwise while generating thumbnail

Original image:

![original image](https://user-images.githubusercontent.com/50202365/107630154-290d7800-6c89-11eb-9897-6b72260ecbfb.jpeg)

Generated thumbnail:

![thumb](https://user-images.githubusercontent.com/50202365/107630213-3cb8de80-6c89-11eb-9c91-97ba3f82d05c.jpeg)

Please let me know if I have to change something.

Thanks in advance.

**Comment by inkhey** [comment]
Hello, Thanks for using preview_generator.
The issue is related to exif rotation metadata. In fact the original image is in landscape but contain some exif rotation metadata, this way your browser is able to display your image in portrait mode.

In current state preview_generator doesn't look at theses metadata, so the rendered preview image:
- doesn't contain exif rotation metadata
- is not either hardly rotated to follow theses infos.

So the rendered image by preview_generator is not rotated the way, you expect.

There is already a pending issue about this:
https://github.com/algoo/preview-generator/issues/166
the proper way to solve this seems to replace exif rotation metadata in generated preview (to have same behavior).

**Comment by AbhijitKulkarni95** [comment]
Hi, Thanks for the reply.

![image](https://user-images.githubusercontent.com/50202365/107641796-0df73400-6c9a-11eb-8b45-1c1ae8398cf1.png)

By adding  image = ImageOps.exif_transpose(image)  in image__Pillow.py I was able to resolve this issue. 

Any idea if this is the right way?

**Comment by lebouquetin** [comment]
> the proper way to solve this seems to replace exif rotation metadata in generated preview (to have same behavior).

@inkhey way you write "replace exif rotation metadata", you mean "copy rotation metadata from original image to thumbnail one"? If so, it looks like this the right way for me too.

**Comment by tonypottera24** [comment]
Any ideas of how to fix this when `wand` is used?

**Comment by AbhijitKulkarni95** [comment]
> Any ideas of how to fix this when `wand` is used?

No idea buddy.

**Comment by tonypottera24** [comment]
I followed your suggestions and add these code before I send files into PreviewManager
```
    try:
        with PILImage.open(image_path) as image:
            image = PILImageOps.exif_transpose(image)
        image.save(image_path)
    except Exception as e:
        print('not a image')
        print(e)
```

**Comment by AbhijitKulkarni95** [comment]
> I followed your suggestions and add these code before I send files into PreviewManager
> 
> ```
>     try:
>         with PILImage.open(image_path) as image:
>             image = PILImageOps.exif_transpose(image)
>         image.save(image_path)
>     except Exception as e:
>         print('not a image')
>         print(e)
> ```
You can upgrade Pillow. It is fixed in the latest version.
pip install Pillow==8.3.1

**Comment by inkhey** [comment]
Image rotation has been introduced by https://github.com/algoo/preview-generator/pull/274
About the fact we should probably keep exif instead of rotating image itself, there is a ticket here : https://github.com/algoo/preview-generator/issues/166
