### ISSUE TITLE
Unsupported mimetype: image/heic

### ISSUE THREAD

**Issue by AbhijitKulkarni95** [algoo/preview-generator#218]
Hi,

I am getting the errors as Unsupported mimetype: image/heic.

Can you please let me know if I am missing anything?

**Comment by inkhey** [comment]
Hello, 

It's complicated to see without much information, where the issue came from. Can you copy/paste the changelog ?

Heic support need a specific configuration in preview_generator, as this is a recent format, you need a imagemagick which support it: https://github.com/algoo/preview-generator/blob/develop/doc/build_im_with_heic_support.rst .
I do hope this will not been required soon but for now, i do think it's still required.

**Comment by AbhijitKulkarni95** [comment]
Hi, 

By following this https://github.com/algoo/preview-generator/blob/develop/doc/build_im_with_heic_support.rst i was able to install dependencies. 

The process returned non-zero exit status 1 when I try to generate for below image. I have zipped the image.

[HEIC_IMAGE.zip](https://github.com/algoo/preview-generator/files/6250178/HEIC_IMAGE.zip)

**Comment by AbhijitKulkarni95** [comment]
Hi @inkhey, 

I have been trying to generate a thumbnail for HEIC and HEIF images for the past few days, but I was not successful.

Can you please check if you are able to generate a thumbnail for this image?

[HEIC_IMAGE.zip](https://github.com/algoo/preview-generator/files/6256433/HEIC_IMAGE.zip)

Please let me know If I am missing something. 

Thanks.

**Comment by AbhijitKulkarni95** [comment]
I was able to get it by installing few other dependencies.

sudo apt-get install build-essential checkinstall \
             libx11-dev libxext-dev zlib1g-dev libpng-dev \
             libjpeg-dev libfreetype6-dev libxml2-dev

Everything works fine now.

Thanks.
