### ISSUE TITLE
Feat: Replace Imagemagick and Pillow by Wand

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#253]
## Feature description and goals

Wand builder as been disabled as it doesn't work as expected.
We may want later to replace both imagemagick and pillow builder by wand as it means less dependencies.
This need many work from the wand side to promote the same quality of result.

**Comment by inkhey** [comment]
some related issue : 
- #134 
- #113 
- #114 
- #115 
- #116 
- #117
- #118

**Comment by lebouquetin** [comment]
We had a talk at the moment.

This issue is interesting in the long term:

- will allow better execution
- will make technical design cleaner

Nevertheless, in the short term this issue has no interest:

- does not add features
- requires work which may be useless (if its not possible to use want, then it will be "lost time")
- will probably generate issues and regressions

**Comment by inkhey** [comment]
fixed by #274
