### ISSUE TITLE
travis: use system package for exiftool instead of using wget

### ISSUE THREAD

**Issue by inkhey** [algoo/preview-generator#38]
actually exiftool is installed manually, that's not correct. We should install it throught system package instead.

**Comment by buxx** [comment]
@basilelegal If i remember correctly, there is a version problem no ?

**Comment by lebouquetin** [comment]
this kind of question should be auto-documented in the code. If we do dirty thinks, it's ok, but it MUST be documented. @basilelegal

**Comment by lebouquetin** [comment]
to complete my remark:

- dependencies must be explicitly defined. If you add dependencies, you must update documentation in order to tell users what package are required.
- dependencies must come from system packages as first option.
- if OS does not furnish a usable dependency (for example because version is too old), then the reason for taking dependancies from somewhere else must be explained in the code and in the documentation.

**Comment by inkhey** [comment]
already fixed by  : https://github.com/algoo/preview-generator/commit/fa55f852a898dc27b6ca8d529a976f1ae7759301
