### ISSUE TITLE
.tar.gz unsupported (and not clear that it is not)

### ISSUE THREAD

**Issue by lebouquetin** [algoo/preview-generator#5]
Testing a .tar.gz json preview results in an AttributeError exception:

```
  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/testpg/venv/lib/python3.4/site-packages/PyPreviewGenerator/manager.py", line 100, in get_json_preview
    return builder.get_json_preview(
AttributeError: 'NoneType' object has no attribute 'get_json_preview'
```

Expected: 

- raise an explicit exception. Example: `NotImplementedError("This file format is currently not supported")` or better, create a specific `UnsupportedFileFormatException` and raise it.

**Comment by herawo** [comment]
I made a builder for the .tar.gz that raises a specific Exception because the mimetype is not supported yet but will be soon because .tar.gz is a basic type of compression file. 
I added a test on the builder to check if it is not a Nonetype (the case when the mimetype given is not supported). 
While browsing the ZipPreviewBuilder I found out that I forgot that I put mimetypes in it without testing them, therefore I put a new issue about it : #8.
